<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Contact:Admin:Contact@addAction'); ?>"><i class="glyphicon glyphicon-phone-alt"></i> <?php $this->show('Add new contact'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 <?php if (!empty($contacts)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Contact:Admin:Contact@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Contact:Admin:Contact@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Contacts')); ?>

<form>
	<div class="table-responsive">
        <?= Grid::render($contacts, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'order',
                    'value' => function($contact){
                        return Element::number(sprintf('order[%s]', $contact->getId()), $contact->getOrder(), array('class' => 'form-control', 'min' => '0'));
                    }
                ),

                array(
                    'column' => 'published',
                    'value' => function($contact){
                        return Element::checkbox(sprintf('published[%s]', $contact->getId()), $contact->getPublished());
                    }
                ),

                array(
                    'column' => 'default',
                    'value' => function($contact){
                        return Element::radio('default', $contact->getId(), $contact->getDefault());
                    }
                )
            ),

            'actions' => array(
                'edit' => function($contact){
                    return Icon::edit(
                        $this->url('Contact:Admin:Contact@editAction', $contact->getId()),
                        $this->translate('Edit this contact')
                    );
                },

                'remove' => function($contact){
                    return Icon::remove(
                        $this->url('Contact:Admin:Contact@deleteAction', $contact->getId()),
                        $this->translate('Remove this contact')
                    );
                }
            )

        ), $this->translator); ?>
		
		<?php if (empty($contacts)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No contacts'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
