<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Contact:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-phone-alt"></i> <?php $this->show('Add new contact'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 <?php if (!empty($contacts)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Contact:Admin:Browser@saveAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Contact:Admin:Browser@deleteSelectedAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Contacts')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center">
						<input type="checkbox" />
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Default'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($contacts)): ?>
			<tbody>
				<?php foreach ($contacts as $contact): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $contact->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $contact->getId(); ?></td>
					<td class="text-center"><?php echo $contact->getName(); ?></td>
					<td class="text-center col-md-2">
                        <?php echo Element::number(sprintf('order[%s]', $contact->getId()), $contact->getOrder(), array('class' => 'form-control', 'min' => '0')); ?>
					</td>
					<td class="text-center">
                        <?php echo Element::checkbox(sprintf('published[%s]', $contact->getId()), $contact->getPublished()); ?>
					</td>
					<td class="text-center">
                        <?php echo Element::radio('default', $contact->getId(), $contact->getDefault()); ?>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this contact'); ?>" data-button="edit" href="<?php echo $this->url('Contact:Admin:Edit@indexAction', $contact->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this contact'); ?>" data-button="delete" href="#" data-id="<?php echo $contact->getId(); ?>" data-category="main"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($contacts)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No contacts'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
